# numPy

It is the fundamental package for scientific computation in python 
It is used to perform numerical and computational purpose
Helps to create multidimensional array

In [2]:
import numpy as np

In [3]:
!pip install numpy

In [6]:
# 1D array -> ,matrix form
np.array([10,20,30])

array([10, 20, 30])

In [5]:
ar_1 = np.array([10,20,30])
print(ar_1)

[10 20 30]


In [8]:
# dtype -> datatype -> datatype inside the array and bit it uses in the memory
ar_1.dtype

dtype('int64')

In [9]:
type(ar_1)

numpy.ndarray

In [10]:
# dimension -> ndim
ar_1.ndim

1

In [16]:
two_ar = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(two_ar)
two_ar.dtype

[[10 20 30]
 [40 50 60]
 [70 80 90]]


dtype('int64')

In [17]:
two_ar.ndim

2

In [18]:
# shape -> column and row
two_ar.shape

(3, 3)

In [22]:
# difference between numpy array and python list
# Main difference
# ar_1+ar_2 -> addition in list list_1+list_2 -> concatation
ar_3 = np.array([10,20,30])
ar_4 = np.array([40,50,60])
ar_3 + ar_4  # addition 

array([50, 70, 90])

In [23]:
list_3 = [10,20,30]
list_4 = [40,50,60]
list_3 + list_4 # concation

[10, 20, 30, 40, 50, 60]

In [27]:
# indexing and slicing
two_ar = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(two_ar)
two_ar[1,2] # indexing

[[10 20 30]
 [40 50 60]
 [70 80 90]]


np.int64(60)

In [30]:
two_ar[0,:] # slicing -> extracting 2D

array([10, 20, 30])

In [31]:
two_ar[0:1,:]

array([[10, 20, 30]])

# Creation of Array

In [32]:
# change the datatype of array
ar_num = np.array([1,2,3,4], dtype = "float")
print(ar_num)

[1. 2. 3. 4.]


In [33]:
ar_num = np.array([1,2,3,4], dtype = "complex")
print(ar_num)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [34]:
ar_num = np.array([1.3,2.5,3.6,4.7], dtype = "int")
print(ar_num)

[1 2 3 4]


In [48]:
#  Creating a array with the help of arange() method 
# Same as range() function
# range(start,end+1,jump) -> table of two -> range(2,21,2)
np.arange(1,11) # we dont use array for 2D 
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
# reshape() -> to change the dimension -> arange it with diff
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
np.arange(31,74,5).reshape(3,3) # 1st draw the size then reshape it according to size 

array([[31, 36, 41],
       [46, 51, 56],
       [61, 66, 71]])

In [52]:
# if you dont know about the column then use (row,-1)
np.arange(1,7).reshape(6,-1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [53]:
# if you dont know about the row then use (-1,colmn)
np.arange(1,7).reshape(-1,6)

array([[1, 2, 3, 4, 5, 6]])

In [54]:
# array of zeros
np.zeros((10)) # array in the float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [55]:
np.zeros((10), dtype="int") # array in the float -> int 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [57]:
# array of ones
np.ones((10), dtype="int")

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [60]:
# array of random element -> normal distribution 
np.array([10,40,7,70])

array([10, 40,  7, 70])

In [61]:
np.random.random(10)

array([0.57416614, 0.39674594, 0.61436873, 0.17238962, 0.96699069,
       0.15938377, 0.34080734, 0.38514248, 0.42809538, 0.05077506])

In [73]:
# This sets the starting point (seed) for random number generation.
# Purpose:
# It makes sure that every time you run the code, you get the same random numbers.
np.random.seed(3)

In [71]:
# This creates a 10 × 5 matrix of random numbers between 0 and 1.
# Part	                          Meaning
# np.random.random	       generate random numbers
# (10,5)	               matrix shape
# 10	                   rows
# 5	                       columns
x = np.random.random((10,5))
print(x)

[[0.2183979  0.82433139 0.99828312 0.99129572 0.15766976]
 [0.47066598 0.70743151 0.34000592 0.69674999 0.74840772]
 [0.81703536 0.84772195 0.08157105 0.30768373 0.56098627]
 [0.91986042 0.09488134 0.40589898 0.53846369 0.64957325]
 [0.30996164 0.84135377 0.49666496 0.7037397  0.67888305]
 [0.62340361 0.9978124  0.15964715 0.81954209 0.3024983 ]
 [0.10592173 0.28630413 0.71360454 0.2384363  0.69766567]
 [0.02552787 0.92849884 0.36307628 0.80005733 0.7195558 ]
 [0.60249053 0.23146103 0.44358768 0.64307498 0.78238398]
 [0.79376227 0.38092887 0.40791699 0.10565921 0.43900271]]


In [72]:
# This generates random integers between 5 and 9.
# Explanation:

# Part	                Meaning
# 5	                 minimum value
# 10	             maximum value (exclusive)
# (5,10)	         matrix size

np.random.randint(5,10,(5,10))

array([[8, 9, 5, 9, 9, 5, 6, 9, 7, 9],
       [7, 9, 5, 8, 9, 7, 6, 6, 8, 5],
       [6, 5, 8, 6, 8, 7, 9, 8, 6, 8],
       [5, 8, 5, 9, 7, 6, 7, 8, 7, 7],
       [9, 6, 9, 7, 6, 8, 6, 7, 7, 8]], dtype=int32)

# Array Attributes

In [77]:
a1 = np.arange(10) # 1D
a2 = np.arange(12,dtype="float").reshape(3,4) # 2D
a3 = np.arange(8).reshape(2,2,2) # 3D
print(a1)

[0 1 2 3 4 5 6 7 8 9]


In [75]:
print(a2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [76]:
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [86]:
# To find the size -> total numbers present inside the array
a1.size

10

In [79]:
a2.size

12

In [80]:
a3.size

8

In [85]:
# to find the shape (no. of rows and column) -> shape 
a1.shape

(10,)

In [83]:
a2.shape

(3, 4)

In [84]:
a3.shape

(2, 2, 2)

In [91]:
# changing the datatype of pre-esisting array -> astype
a2.astype(np.int64)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
# multiply elements 
a2=np.arange(12,dtype="int").reshape(3,4)
x=a2*3
print(x)

[[ 0  3  6  9]
 [12 15 18 21]
 [24 27 30 33]]


In [103]:
# check out elements greater than 15 
print(x > 15 )

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]


In [108]:
# addition and substraction 
a4 = np.arange(12,24).reshape(3,4)
a4 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [109]:
a4 - a2

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

# Array Functions

In [112]:
# prod -> To do product of elements present in the array 
from numpy.core.fromnumeric import prod
print(np.prod(a2)) # becz it contain zeroo -> any thing multiply by zero is zero 

0


C:\Users\Siddhi\AppData\Local\Temp\ipykernel_33784\450966220.py:2: DeprecationWarning: numpy.core.fromnumeric is deprecated and has been renamed to numpy._core.fromnumeric. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.fromnumeric.prod.
  from numpy.core.fromnumeric import prod


In [111]:
print(np.prod(a4))

647647525324800


In [115]:
# Minimum and maximum
print("Minimum:" , np.min(a2))
print("Minimum:" , np.min(a4))
print("Maximum:" , np.max(a2))
print("Maximum:" , np.max(a4))

Minimum: 0
Minimum: 12
Maximum: 11
Maximum: 23


In [117]:
# sum and mean -> average
print("sum: " , np.sum(a2))
print("mean:", np.mean(a2))

sum:  66
mean: 5.5


In [118]:
# finding mean across rows(axis=1) and column(axis=0)
print("mean across rows: ", np.mean(a2,axis=1))
print("mean across columns: ", np.mean(a2,axis=0))

mean across rows:  [1.5 5.5 9.5]
mean across columns:  [4. 5. 6. 7.]


In [123]:
# standard deviation -> it the measure of how much variation exists from the mean of a data
print("\"S.D:\"", np.std(a2))
# variance
print("\"Variance\":", np.var(a2))

"S.D:" 3.452052529534663
"Variance": 11.916666666666666


# Matrix Operations

In [127]:
# dot product of two matrix -> multiplication scalar values
a5 = np.arange(15).reshape(3,5)
a6 = np.arange(15).reshape(5,3)
result = np.dot(a5,a6)
print(result)

[[ 90 100 110]
 [240 275 310]
 [390 450 510]]


In [131]:
# how to iterate over the matrix 
# for loop -> 2D in nature , uses nested list
mat = a5 = np.arange(4).reshape(2,2)
for i in mat:
    print(i)

[0 1]
[2 3]


In [132]:
# Iterating Each Element (Nested Loop)
# If you want to access every element, use a nested loop.

for i in mat:
    for j in i:
        print(j)

0
1
2
3


In [133]:
# Using NumPy Iterator (nditer) -> iterate in nested loop
# NumPy also provides a special iterator.

for element in np.nditer(mat):
    print(element)

0
1
2
3


In [135]:
# how to convert 1D to 2D -> reshape
# how to convert 2D to 1D -> ravel
x = mat.ravel() # 2D -> 1D
print(x)

[0 1 2 3]


# HOME WORK : Stacking and splitting refer from pdf 